//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryectoMovieTheater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int IdUser { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual TipeCount TipeCount { get; set; }
    }
}
