//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryectoMovieTheater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipeCount
    {
        public int Idtipe { get; set; }
        public string User { get; set; }
        public string Admin { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
