//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryectoMovieTheater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpData
    {
        public int IdIngreso { get; set; }
        public string Titulo { get; set; }
        public string Ubicacion { get; set; }
        public string Caratula { get; set; }
        public string Genero { get; set; }
        public Nullable<System.DateTime> Año { get; set; }
        public string Sinopsis { get; set; }
    
        public virtual Generos Generos { get; set; }
    }
}
